### ISSUE TITLE
Pat Fish Institution + New mixes from Rolo Coming soon

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#100]
Photos courtesy of Philip Snow posted on Facebook

![Screen Shot 2022-05-17 at 8 39 27 PM](https://user-images.githubusercontent.com/93959968/168952407-aa1408eb-27e1-4284-8e27-16a8b7c76fc0.png)

![Pat Fish -  Insitution](https://user-images.githubusercontent.com/93959968/168946979-fa4c2129-f441-4a9c-b483-7427d7b569ef.jpg)
![282000833_3185487025041534_3807369563049152312_n](https://user-images.githubusercontent.com/93959968/168952073-8425dc97-28cf-412e-b1ea-10da54b60ac3.jpg)
![281581877_3185487008374869_6324991462387254061_n](https://user-images.githubusercontent.com/93959968/168952077-93f20122-b70b-4542-b14e-3d420bc85bf3.jpg)

![Screen Shot 2022-05-17 at 7 43 44 PM](https://user-images.githubusercontent.com/93959968/168946983-a275e08c-26cb-41ec-a976-cd89db8fd5e8.png)

![Screen Shot 2022-05-17 at 11 46 16 PM](https://user-images.githubusercontent.com/93959968/168975419-0abf4a0c-520c-426c-b8b0-488fcd83a05f.png)

![Rolo talks Institution-1](https://user-images.githubusercontent.com/93959968/168947563-0b64adab-b338-4f17-990d-f59200b689ab.png)
![Rolo talks Institution-2](https://user-images.githubusercontent.com/93959968/168947787-e725f1a5-4c7e-4ae2-b6b8-54a896264fc9.png)
![Rolo talks Institution-3](https://user-images.githubusercontent.com/93959968/168947801-40a8df6a-b257-4103-abff-7cce0cdf1248.png)

**Comment by xpollen8** [comment]
@Bigquestionsinc Hey James... wanna hit Rolo up to see if those Institution tapes are digitized yet?

I've got a home for them!

**Comment by xpollen8** [comment]
All above content added to JBC com V2

**Comment by Bigquestionsinc** [comment]
xpollen8,      Good idea! I’m on the road in Austin at the moment and then NYC. I’ll message Rolo and connect the two of you! I want to connect you with Simon as well who has all the Highest In The Land and JBQ demos. I’m actually dying to hear all this stuff!!   I have another email coming your way regarding Sonic Tonix and The Tonix!   I hope you are well my friend! Talk you you soon!   Love & Respect,        Jimmy xxOn Sep 23, 2023, at 6:08 PM, xpollen8 ***@***.***> wrote:﻿
@Bigquestionsinc Hey James... wanna hit Rolo up to see if those Institution tapes are digitized yet?
I've got a home for them!
