### ISSUE TITLE
Sister Death Pat's handwritten lyrics

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#103]
I just received these handwritten lyrics from Mr. Curtis E Johnson himself! 
They are from the hand of the man himself and gratefully received. I will be getting
this famed this week.

Higher Quality Scan coming soon

[Sister Death Lyrics](https://user-images.githubusercontent.com/93959968/185761861-2062d4e8-a114-438c-8567-89ce833b6021.JPG)

Higher quality scan - 
![Sister Death Scan](https://user-images.githubusercontent.com/93959968/185845831-34287139-aec9-4955-91ca-8c6196dacb8b.jpeg)

**Comment by xpollen8** [comment]
Included in JBC com V2!
