### ISSUE TITLE
Tribute song about Pat Fish by Pete Astor: Fine and Dandy – video premiere

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#105]
A song about Pat Fish by Peter Astor Just posted on louder than war - 

https://louderthanwar.com/pete-astor-fine-and-dandy-video-premiere-a-song-about-pat-fish/?fbclid=IwAR2nNdeUIaO0ir9UNE2CE-8XNHc6XHLP0fdkrvpFoIJrFl3kCByflsYYdiA

**Comment by xpollen8** [comment]
In JBC com V2
