### ISSUE TITLE
Pat's 1st show ever!?

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#106]
This was posted by a gentleman named Chris Zero on The Jazz Butcher Facebook Group.
There is much to share with you from the page. I've just been so slammed with work. Which is good.

"Patrick's first ever performance, 1974 Uppingham, 
age 17, with 'Chris Zero' and 'others' inc. 'Rolo' on synth.

![Jazz Butcher Facebook page](https://user-images.githubusercontent.com/93959968/194727388-9960d188-2ae9-4eb5-ab65-5398ef2cae0e.jpg)

![Pat and Chirs Zero?-1](https://user-images.githubusercontent.com/93959968/194727389-b805f987-e184-4f8c-bfe8-de08b5566a52.jpg)

![Pat and Chris Zero? - 2](https://user-images.githubusercontent.com/93959968/194727391-9ba83c2d-0eea-47e7-b1d3-54114473ff30.jpg)

![Rolo on keys, ? on Bass ](https://user-images.githubusercontent.com/93959968/194727392-6ac81a18-e492-4858-a33f-f70bb5ef1731.jpg)

**Comment by xpollen8** [comment]
images uploaded (not yet categorized)

keep 'em coming!

**Comment by xpollen8** [comment]
Incorporated into JBC com V2
