### ISSUE TITLE
Never Give Up (Early One Take demo)

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#107]
Whew! This one is a whopper! It just came up on the Jazz Butcher Facebook Group. Posted by the illustrious Simon Taylor himself. A very early rendition of "Never Give Up" before the lyrics "Never Give Up" were sang and an extra verse at the end. He edited together a beautiful heart wrenching video to accompany the song with images of Pat and the Band together on tour. There should be a youTube video up soon and I will ad the link.

![Never Give Up Early version](https://user-images.githubusercontent.com/93959968/195912958-73ff7078-7881-4a78-b7f3-34c714395f09.png)

https://www.facebook.com/583232796/videos/5903366906363551/

**Comment by xpollen8** [comment]
@Bigquestionsinc - I was able to grab the (public) video and am currently uploading to the JBC uploader. Not half bad.

Could you please: ask Simon to get in touch w/me (email).  He seems he would be a source for material from that era.  The pix featured in that video - almost none have been seen before and I'd love to have copies of originals.

Thanks for adding this!

**Comment by Bigquestionsinc** [comment]
Whew!
    That's Great! I wasn't sure if you'd be able to see the video! You got it! I will message Simon and ask him 
to contact you. I would nothing more than to hear/see more material from that era.
   I'm trying to keep up with everything that's been posted (inbetwen jobs) so there's a bit more for me to 
catch you up on. Thankfully you're in touch with Philip Snow and Dihren Basu who are incredibly generous 
with sharing from their deep reservoir of material. And with more coming onboard ie: Dave Barker, Rolo McGintyand John Silver among others.
   We need to have a proverbial round-table soon and figure out how to shake loose all that unreleased stuff sittingin Pat's attic. 
          "Belgian Congo"          "Elephant Man"          "Sheep May Safely Gaze Where The Railway Was"          "??"Big Planet demo that didn't work in the studio          "Cat Brand Meditation" ( i beleve Brian Kelly has a copy of this demo)          " I Never Know When To Say When"          "Over The Rainbow" (Lovebus sessions)
           Philip Snow mentioned he might have the following in some form - 

          "Teddy"          "I'm An Idiot'          "You Can't Hurt Me"          "Over The Rainbow's End"
         
   and many others to be sure. Again, I've been meaning to try and gather a proverbial round-tableto discuss gathering all this material together but my schedule has been so full I haven't had to 
time to try and arrange it. Hopefully sometime soon.  


   I hope you are having a good week, David and I'll talk to you soon!

                 Jimmy xx

 On Friday, October 14, 2022 at 11:46:01 AM PDT, xpollen8 ***@***.***> wrote:  
 
 


@Bigquestionsinc - I was able to grab the (public) video and am currently uploading to the JBC uploader. Not half bad.

Could you please: ask Simon to get in touch w/me (email). He seems he would be a source for material from that era. The pix featured in that video - almost none have been seen before and I'd love to have copies of originals.

Thanks for adding this!

**Comment by xpollen8** [comment]
All noted for inclusion in JBC com V2 - Thanks!
