### ISSUE TITLE
Senor Hobbu website?!

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#109]
https://hobbu.com/senor.html
With 3 neat links including the lyrics to the Hobbu song!

![Screen Shot 2022-12-22 at 5 02 43 PM](https://user-images.githubusercontent.com/93959968/209250587-07736995-4d51-4281-9d3e-bb0259f9d610.png)

![Screen Shot 2022-12-22 at 5 04 08 PM](https://user-images.githubusercontent.com/93959968/209250672-629dd6bf-ab1d-40d8-9434-afbefb733880.png)

**Comment by xpollen8** [comment]
Consider hobbu.com already backed-up.  I have hosted that silly site since 2000(!)
