### ISSUE TITLE
The Jazz Butcher "Earl Sikkorski" Fan Club letter!

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#110]
I just came across this on Facebook this morning! 
Brought to us by the incredible Heidi Rosen from The Jazz Butcher Facebook Group!
Long Live The JBC fans!!

![JBC fan club - 1](https://user-images.githubusercontent.com/93959968/215290386-c90e3b9a-2ecc-4724-888a-ee11e32d0c0a.jpg)
![JBC fan club - 2](https://user-images.githubusercontent.com/93959968/215290388-ef0dc2f8-465a-4e1e-be07-d6b3508e498f.jpg)
![JBC fan club - 3](https://user-images.githubusercontent.com/93959968/215290390-8567cfc0-b4e0-403f-8d95-e04c53622ee8.jpg)
![JBC fan club - 4](https://user-images.githubusercontent.com/93959968/215290392-92beb15d-7bf6-4723-b409-ba58e1e2f096.jpg)
![JBC fan club - 5](https://user-images.githubusercontent.com/93959968/215290441-5c40e5e6-0f5e-4aaf-a404-2ef0ebcb0a92.jpg)

**Comment by xpollen8** [comment]
Thanks Jimmy! Incorporating into JBC com V2
