### ISSUE TITLE
Bootleg: JBC at Odd Rock Cafe, Milwaukee WI USA June 12, 1988

### ISSUE THREAD

**Issue by djbuege** [xpollen8/jazzbutcher.com#111]
The set list is quite different than the one posted at jbc.com.  I was there and this recording reveals the truth.  Folder with all tracks will be uploaded soon.

**Comment by xpollen8** [comment]
It is ok to send it up as an entire show (single track) if you've got that as well.

Thanks!

**Comment by xpollen8** [comment]
Wow, this is a wonderful show, lots of chatting w/the crowd.  And one of the earliest performances of Girl-Go - still sorting out the lyrics!

Check it, @presto211 and @Bigquestionsinc 

https://jazzbutcher.com/gigs/1988/Jun12.html
