### ISSUE TITLE
antisyzygy 20180301 flickr

### ISSUE THREAD

**Issue by xpollen8** [xpollen8/jazzbutcher.com#112]
WHO: djbuege found it, antisyzygy posted WHEN: March 1, 2018

https://www.flickr.com/photos/antisyzygy/

_Originally posted by @djbuege in https://github.com/xpollen8/jazzbutcher.com/issues/10#issuecomment-1440888028_

**Comment by xpollen8** [comment]
Lots of pix here. Wish there were a way to bulk download. Sigh

**Comment by djbuege** [comment]
I can tackle it in next few days.  I'll download them, zip em and load em
up.

**Comment by xpollen8** [comment]
Just the pix w/Pat in them, plz. There were other bands playing that night.

**Comment by djbuege** [comment]
Uploaded the images with PF from March 1, 2018.  There are more from earlier dates that I'll get soon.
Contacted poster antisyzygy but did not hear back.

**Comment by xpollen8** [comment]
Antiszygy is a longtime site contributor. They should respond.

**Comment by xpollen8** [comment]
Got 'em and deduped. THANKS and THANKS FOR WAITING.

the results will be reflected on JBC com V2 (in progress)
