### ISSUE TITLE
The Jazz Butcher & His Big Soppy Pussycats  Zombie Love - Love Kittens - Roadrunner live 12-18-82

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#116]
The Jazz Butcher & His Big Soppy Pussycats  - Zombie Love - Love Kittens - Roadrunner 

Live at the Glass Records Christmas Party, The Black Lion, Northampton, December 18, 1982
Pat Fish
Max Eider
Louis Leroi
Ian Sturgess
Lionel Brando

Posted on the Jazz Butcher Facebook group this morning and shared on soundcloud by 
Dave (Lionel Brando) Barker himself!

![Screen Shot 2023-04-14 at 9 33 49 AM](https://user-images.githubusercontent.com/93959968/232103825-0d371e73-c5b9-4062-ab72-4dde60a32266.png)

https://soundcloud.com/user-46834996/the-jazz-butcher-his-big-soppy-pussycats-zombie-love-love-kittens-roadrunner/s-VbAeD7eLGQi?fbclid=IwAR21LWnJ-aqahtE1djeTk4dr1b09dzVBTAIpIZL-aJy5cbFw8WFZVRckRGM

**Comment by xpollen8** [comment]
Got it, thanks!

https://jazzbutcher.com/gigs/1982/Dec18.html
