### ISSUE TITLE
J.B.C. live at the Alabama Halle Munich Germany 11 November 1985

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#117]
Finally got around to uploading this gig onto youtube.
J.B.C. live at the Alabama Halle Munich Germany 11 November 1985

https://www.youtube.com/watch?v=bPwISvRlXfw

Setlist-
    1. Girlfriend 
    2. Bigfoot Motel 
    3. The Human Jungle 
    4. Walk with the Devil 
    5. Partytime 
    6. Marnie 
    7. Death Dentist 
    8. Still in the Kitchen 
    9. Zombie Love 
    10. Speedy Gonzalez

**Comment by xpollen8** [comment]
All updated, thanks, James!
