### ISSUE TITLE
New Youtube show - THE JAZZ BUTCHER The Richmond Brighton 13th November 1984

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#131]
WOW! AWESOME unknown live show of The Sikkorskis!

THE JAZZ BUTCHER The Richmond, Brighton UK 13th November 1984 

-Posted Oct 12, 2023 on Youtube!
https://www.youtube.com/watch?v=yXO4qSElFAU

The Butcher
Max Eider
David J
Owen Jones

THE JAZZ BUTCHER The Richmond Brighton 13th November 1984
1. Southern Mark Smith
2. Bigfoot Motel
3. Real Men
4. Marnie
5. Partytime
6. Girlfriend
7. Leaving It Up To You
8. Only A Rumour
9. Red Pets
10. Rain
11. I Need Meat
12. Zombie Love
13. Love Kittens intro/Roadrunner (Encore) -fades out before end

**Comment by xpollen8** [comment]
Perfect, thank you.  I wonder why this was never on Pat's lists.
