### ISSUE TITLE
Never Give Up - Uncropped Painting by Sophie Joiner

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#137]
Posted on Facebook Dec 20, by David Barker -
  ·   ·
Today would have been Patrick's 66th Birthday. Here's the original uncropped painting by Sophie Joiner for the sleeve of 'Never Give Up". Happy birthday old sport, wherever you are ❤️

![Never Give Up Painting](https://github.com/xpollen8/jazzbutcher.com/assets/93959968/00049079-837c-43b6-8f13-e8e74376709f)

**Comment by xpollen8** [comment]
Gotcha - jazzbutcher.com/releases/never_give_up
