### ISSUE TITLE
Bootlegs here: http://www.dimeadozen.org/index.php

### ISSUE THREAD

**Issue by xpollen8** [xpollen8/jazzbutcher.com#40]
There are a few high-quality bootlegs available on this site.

You will need an account.

Either open up a new Issue for each "thing", or attach results one-per-comment on this issue.

Always attribute:

WHO/WHEN/URL

Large files to Dropbox and add a link here

**Comment by wnerini** [comment]
Signed up and requested upgrade from guest. Will start downloading when I am approved on the newest file (with good ratio a possibility) and delay older files until Dec 21st, when they have a "freeloader" party.

**Comment by wnerini** [comment]
Account is upgraded. Starting to build my ratio (just getting something ultra-new). Shouldn't take much time. I definitely want to be a good citizen there, not just for Pat's sake but because that place has some bloody awesome content. ☠️

**Comment by xpollen8** [comment]
![6](https://user-images.githubusercontent.com/552254/141413594-9cae6963-e612-4fcb-b81b-b0e5f6add544.png)
![5](https://user-images.githubusercontent.com/552254/141413604-d5608c47-5a9a-4c0b-b355-866025371c46.png)
![4](https://user-images.githubusercontent.com/552254/141413610-d83a167d-56c5-4daf-a276-4cd49ca1fb7d.png)
![3](https://user-images.githubusercontent.com/552254/141413615-337745e6-1beb-4f13-a92d-de001a6bf7de.png)
![2](https://user-images.githubusercontent.com/552254/141413619-f5f3b8f1-1caf-41a3-b21b-fb529c73ed63.png)
![1](https://user-images.githubusercontent.com/552254/141413625-88060eb7-a8f0-40e6-95f2-9f1a26815877.png)

**Comment by wnerini** [comment]
Wetlands uploads, mp3, zip (with flac) and info text.

**Comment by wnerini** [comment]
Roxy Uploaded. 

Files (should be):
JBC 1990-11-23 The Roxy, Hollywood, CA.mp2
JBC 1990-11-23 The Roxy, Hollywood, CA.zip
JBC 1990-11-23 The Roxy, Hollywood, CA info.txt

**Comment by wnerini** [comment]
Batschkapp - Frankfurt Uploaded.

Files (should be):
The Jazz Butcher - 1985-11-16 - Batschkapp - Frankfurt, DE.mp3
The Jazz Butcher - 1985-11-16 - Batschkapp - Frankfurt, DE.txt
The Jazz Butcher - 1985-11-16 - Batschkapp - Frankfurt, DE.txt

**Comment by wnerini** [comment]
JBC - 1988-03-24 - Metropol - Aachen, DE Uploaded

Files (should be):
JBC - 1988-03-24 - Metropol - Aachen, DE.mp3
JBC - 1988-03-24 - Metropol - Aachen, DE.txt
JBC - 1988-03-24 - Metropol - Aachen, DE.zip

**Comment by wnerini** [comment]
The Jazz Butcher - 2018-05-27 - 100 Club, London Uploaded

Files (should be):
The Jazz Butcher - 2018-05-27 - 100 Club, London.mp3
The Jazz Butcher - 2018-05-27 - 100 Club, London.txt
The Jazz Butcher - 2018-05-27 - 100 Club, London.zip

**Comment by wnerini** [comment]
The Jazz Butcher - 1985-08-23 - Zeche Bochum - Bochum, DE Uploaded

Files (should be):
The Jazz Butcher - 1985-08-23 - Zeche Bochum - Bochum, DE.mp3
The Jazz Butcher - 1985-08-23 - Zeche Bochum - Bochum, DE.txt
The Jazz Butcher - 1985-08-23 - Zeche Bochum - Bochum, DE.zip

**Comment by xpollen8** [comment]
Excellent beaving, Will.  I'l take it from here.

**Comment by xpollen8** [comment]
> The Jazz Butcher - 2018-05-27 - 100 Club, London Uploaded
> 
> Files (should be): The Jazz Butcher - 2018-05-27 - 100 Club, London.mp3 The Jazz Butcher - 2018-05-27 - 100 Club, London.txt The Jazz Butcher - 2018-05-27 - 100 Club, London.zip

deployed: http://jazzbutcher.com/gigs/2018/May27_1930.html

**Comment by xpollen8** [comment]
> Batschkapp - Frankfurt Uploaded.
> 
> Files (should be): The Jazz Butcher - 1985-11-16 - Batschkapp - Frankfurt, DE.mp3 The Jazz Butcher - 1985-11-16 - Batschkapp - Frankfurt, DE.txt The Jazz Butcher - 1985-11-16 - Batschkapp - Frankfurt, DE.zip

deployed: http://jazzbutcher.com/gigs/1988/Mar24.html

**Comment by wnerini** [comment]
> deployed: http://jazzbutcher.com/gigs/2018/May27_1930.html
> 
> @wnerini - The .txt hints at the name of the bootlegger (one of the Jowe Head band), but the name isn't in the .txt - any idea?

Doesn't say anywhere I can find. I pinged the original uploader to see if they know.

**Comment by wnerini** [comment]
> deployed: http://jazzbutcher.com/gigs/1988/Mar24.html

@xpollen8 - Link goes to the Metropol Aachen show, not the Batschkapp show. Link has correct audio for the Metropol show. 😄

**Comment by xpollen8** [comment]
> > deployed: http://jazzbutcher.com/gigs/1988/Mar24.html
> 
> @xpollen8 - Link goes to the Metropol Aachen show, not the Batschkapp show. Link has correct audio for the Metropol show. 😄

yeah - i just quote replied to the wrong git entry - JBC site is correct

**Comment by xpollen8** [comment]
> Roxy Uploaded.
> 
> Files (should be): JBC 1990-11-23 The Roxy, Hollywood, CA.mp3 JBC 1990-11-23 The Roxy, Hollywood, CA.zip JBC 1990-11-23 The Roxy, Hollywood, CA info.txt

This one has been added to the site: https://jazzbutcher.com/gigs/1990/Nov23.html

Others will be as time permits.  THANK YOU (very belatedly)
