### ISSUE TITLE
Fishy Mansions sessions

### ISSUE THREAD

**Issue by xpollen8** [xpollen8/jazzbutcher.com#43]
Back these up!

This service seems to work ok: https://www.fdown.net/

Download:
no9 √ July 25, 2021 - https://www.facebook.com/rock.music.fan2/videos/4727131967305769                                                                           
no8 √ June 6, 2021 - https://www.facebook.com/rock.music.fan2/videos/4728666337167175                                                                           
no7 √ (was SD, not HD like the others) April 18, 2021 - https://www.facebook.com/rock.music.fan2/videos/10225946186143310                                                            
no6 √ Feb 21, 2021 - https://www.facebook.com/rock.music.fan2/videos/931396580795641                                                                
no5 √ New Years 2020 - https://www.facebook.com/rock.music.fan2/videos/301108121450060  
no4 √ (was SD) Dec 6 - https://www.facebook.com/pat.fish.7/videos/10215055466938469 **(PRIVATE!)**                                              
no3 √ Sept 28 - https://www.facebook.com/rock.music.fan2/videos/1024675418375453                                         
no2 √ July 12, 2020 - https://www.facebook.com/rock.music.fan2/videos/931481747497430                                                               
no1 √ June 14, 2020 - https://www.facebook.com/rock.music.fan2/videos/660179644944727   

Then send to S3:
√ no1
√ no2
√ no3
√ no4
√ no5
√ no6
√ no7
√ no8
√ no9

**Comment by MomboMan** [comment]
This is a link to [#4](https://www.dropbox.com/s/rs87ex8kx30p2ia/JazzButcher%20-%2012-2020.mp4?dl=0)

Let me know if something isn't right.

Cheers

Craig D

**Comment by xpollen8** [comment]
> This is a link to [#4](https://www.dropbox.com/s/rs87ex8kx30p2ia/JazzButcher%20-%2012-2020.mp4?dl=0)
> 
> Let me know if something isn't right.
> 
> Cheers
> 
> Craig D

Ah, heck yeah. Thanks a bunch.  Uploading to S3 right now.

Hey - Was an HD version of that video available?  It (along with 2021-04-18) is in the smaller SD format.

No biggy - I'll take what you got if that's all there is.

Thanks again

**Comment by MomboMan** [comment]
I have no idea about an HD version.  Somebody was posting them right after Pat died and I managed to grab 3 of them.  

And you're welcome.
