### ISSUE TITLE
Missing "Fishy Mansions"...? 2020-08-16 - Is there a FB video?

### ISSUE THREAD

**Issue by xpollen8** [xpollen8/jazzbutcher.com#50]
setlists.fm notes this one..

https://www.setlist.fm/setlist/the-jazz-butcher/2020/private-venue-northampton-england-5b85b788.html

TASK: Is there a Facebook video for this apparent 2020-08-16 gig?

If so, please download the vide (HD) and upload to Dropbox and leave the link here.

**Comment by wnerini** [comment]
Yes, there is. Would you like me to upload the video?

**Comment by wnerini** [comment]
Hmm,,,

- I don't remember an August gig
- I've checked all my downloaded shows, and none august gig
- I've checked all my downloaded shows, and nothing with that short of a playlist (or any portion of that list)
- I've checked FB where Oksana Kozachenko uploaded her complete archive and can't find this show
- The setlist is extremely brief, compared to other Fishy Mansions shows

This may be a semi-private or non advertised show, but I can't find mention of it anywhere but on setlist.fm.

**Comment by wnerini** [comment]
Additionally, here is what I believe is a complete list of the "Fishy Mansions" shows. Does not include the 3 Q&As.

Pat Fish fb show, July 2021
Pat Fish fb show, June 2021
Pat Fish fb show, April 2021
Pat Fish fb show, February 2021
Pat Fish fb show, New Year's Eve 2020
Pat Fish fb show, December 2020
Pat Fish fb show, September 2020
Pat Fish fb show, July 2020
Pat Fish fb show, June 2020

**Comment by xpollen8** [comment]
| the 3 Q&As.

Will - are there additional FB livestreams (these QA jobbers)?

If so, can you paste their URLs here and I'll see if I'm able to grab them.

Thanks for chasing down what may have been a red herring.

**Comment by xpollen8** [comment]
NM - I found the Q/A sessions on 'tube.

https://www.youtube.com/watch?v=AMlH7YdhjpI
etc
