### ISSUE TITLE
Solo, Acoustic Performance At The Constitution, London 6 March 2012.

### ISSUE THREAD

**Issue by wnerini** [xpollen8/jazzbutcher.com#52]
From Raj Patel (Flutterechoes on YouTube)

"As promised a week or so ago, I have uploaded all the videos from the night in London when Pat Fish played "Sex and Travel" at The Constitution, London 6 March 2012. It's missing two songs, "Holiday" and "What's The Matter Boy".  "Holiday" I was watching intently camera off, because in 1995 I had travelled from Hong Kong to London over land on the Trans Siberian Express, and listened a lot to that song and corresponded with Pat on the journey.  He invited me out one evening shortly after returning and expressly asked me to bring all my photos from the trip.  Over several Pilsners he wanted to know the story behind every one, another unforgettable evening with him.  The latter is missing for the boring reason of almost no battery left and decided to save it for the last two songs.  I hope you enjoy watching."

YouTube Playlist: https://www.youtube.com/playlist?list=PLf2KmC7lTM5bCT5w8FCn1uKPLPauyDiOz

**Comment by xpollen8** [comment]
Deployed: http://jazzbutcher.com/gigs/2012/Mar6.html

**Comment by wnerini** [comment]
Awesome, thanks!
