### ISSUE TITLE
Andy Cowan OBIT

### ISSUE THREAD

**Issue by xpollen8** [xpollen8/jazzbutcher.com#58]
https://twitter.com/glassmodern1/status/1459187934049947650

TASK: [upload the image](https://upload.jazzbutcher.com/) and then run it through [an online OCR servivce](https://www.onlineocr.net/) to convert the image to **TEXT** (not word doc).

Attach output of the OCR as a comment to this issue.

Thanks!

**Comment by aaroach** [comment]
[The_Jazz_Butcher_MOJO_Tributre.txt](https://github.com/xpollen8/jazzbutcher.com/files/7540511/The_Jazz_Butcher_MOJO_Tributre.txt)

**Comment by aaroach** [comment]
JPG to be  uploaded via Uploader

**Comment by xpollen8** [comment]
FINALLY GOT TO IT.  Thank you
