### ISSUE TITLE
Review: 'A Celebration Of Pat Fish (The Jazz Butcher)' 'Live at The Dublin Castle Camden' link

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#67]
http://www.whisperinandhollerin.com/reviews/review.asp?id=15747&fbclid=IwAR38LQMvNfg6vx6oS3uGUu8HA8pCC5FiTNwX_IdTdVzFmVpQ4CJ2y-nTJqs

**Comment by xpollen8** [comment]
TY! Keep 'em coming

**Comment by xpollen8** [comment]
Added: http://jazzbutcher.com/press/20211127_press_tribute.html
