### ISSUE TITLE
Tonix Poster 80-81 John Silver, Pat Fish, Dave Goldie, Peter Millson (Max), Owen Jones

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#68]
Owen Jones posted this on facebook. Awesome early Tonix (Pre-Jazz Butcher) poster.

**Comment by xpollen8** [comment]
Looking forward to seeing this!  Attach it here, or drop it over at upload.jazzbutcher.com

Thanks!

**Comment by Bigquestionsinc** [comment]
[](url
![The Tonix 80-81 John Silver, Pat, Dave Goldie, Max and Owen](https://user-images.githubusercontent.com/93959968/144690351-8d2a9fc6-1daf-42b8-9851-9aaee90a9c9e.jpg)
)

**Comment by Bigquestionsinc** [comment]
Oops, sorry about. I forgot to attach the image!
