### ISSUE TITLE
Vaguely Familiar master tape images from Richard Formby

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#71]
Posted by Richard Formby in the JBC facebook group

![The Vaguely Familiar tapes-1](https://user-images.githubusercontent.com/93959968/145637645-d69b1a10-4150-4cdf-88f5-2b7918cacc58.jpg)
![The Vaguely Familiar Tapes-2](https://user-images.githubusercontent.com/93959968/145637651-97302e04-771f-4add-af91-a707ae655f8f.jpg)
.

**Comment by xpollen8** [comment]
Woot: http://jazzbutcher.com/gigs/1991/Jul.html

**Comment by Bigquestionsinc** [comment]
Looks Great! Also there is a Jazz Butcher listening party tomorrow at 2pm (PST) on google with Thomas Peterson sharing a bunch of old demos he got from Pat years ago including Pat doing Pyscho Killer! Let me know if you wanna join us and I'll send you the link. Preparing to upload a bunch of new stuff to github as well! 

     I hope you are doing well Dave!
  Cheers,
           Jimmy

    On Friday, December 10, 2021, 04:14:55 PM PST, xpollen8 ***@***.***> wrote:  
 
 


Woot: http://jazzbutcher.com/gigs/1991/Jul.html

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xpollen8** [comment]
Yes please on the listening party

**Comment by Bigquestionsinc** [comment]
You got it my friend! I'll send over the link in the next hour or two when 
Thomas sends it to me. Also, I've been talking to a man name Philip Snow 
from the Jazz Butcher Facebook group and he has/had been working with Pat 
on a 190,000 word manuscript of all Pat's songs, including ideas and concepts 
called, "MIRACLES & WONDERS". And, it's ready to go! He just needs help looking for a publisher. I'm trying my best to help out in that department as well. 
This book sounds absolutely brilliant!! Fresh news as he just emailed me about it. I hope you had a good weekend.

  I'll talk to you soon!
              Jimmy
    On Saturday, December 11, 2021, 04:55:52 PM PST, xpollen8 ***@***.***> wrote:  
 
 


Yes please on the listening party

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Bigquestionsinc** [comment]
Hello David!
    Here is the link 

https://meet.google.com/ggx-fzeq-zuf?fbclid=IwAR0avXf7-3QlqPWJwiqttFzWYeLElJwrp37Dgu5P6iyomEEpRdGOEgoPulg
    Starts at 2pm! I look forward to seeing you on there!

  Cheers,
        Jimmy
    On Saturday, December 11, 2021, 04:55:52 PM PST, xpollen8 ***@***.***> wrote:  
 
 


Yes please on the listening party

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
