### ISSUE TITLE
Pat Fish Tonix Pic posted by Owen

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#73]
Here is an image posted by Owen of Pat singing in The Tonix circa 1980-1981. I included the original and a cleaned up version done by Phil Wilson "The Perfect Disaster" himself
![Pat Tonix Carribean Club Oxford 1980-1](https://user-images.githubusercontent.com/93959968/145693987-161c3a65-7844-4add-ac60-168f7f66e41b.jpg)
![Pat Tonix Carribean Club Oxford 1980-2](https://user-images.githubusercontent.com/93959968/145693989-77ded42f-7067-4d3c-8c64-289911232d4f.jpg)
!

**Comment by Bigquestionsinc** [comment]
Owen Jones wrote "Pat singing with The Tonix - Caribbean Club, Oxford, 1980. Photo by Tony Kirman (that unpleasant looking stain is on my print of the photo, not on Pat's jacket..)"

**Comment by xpollen8** [comment]
moved into place - thanks again!
