### ISSUE TITLE
Owen Posted JBC Onkel Pö Dec 1985 Pic

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#74]
Owen P. Jones wrote on Dec 8 - Pat, me and Max at the wonderful Onkel Pö club in Hamburg - which is where, as it it happens, I met the love of my life Bärbel, 37 years ago today..

Owen P. Jones also wrote Dec 8 - Not 100% certain, but I think the photo was taken by Alistair Indg

![Pat, Owen and Max Onkel Po Dec 4 1985?](https://user-images.githubusercontent.com/93959968/145694138-a11d6da7-0ba4-4dbb-8dc2-2bc5b75887a0.jpg)
e

**Comment by xpollen8** [comment]
WOWOWOWOWO

**Comment by xpollen8** [comment]
http://jazzbutcher.com/gigs/1984/Dec8.html
