### ISSUE TITLE
The Institution and Sonic Tonix record images/songs

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#76]
Images for The Institution - "Jane And Jon/Stephanie" (generic white sleeve signed by Pat) cat# SGS-112 on the DIY label Industrial accident 1979. These are old images. I will make better, high quality pics/scans (once I pull my box of 7" 45's out of the closet) and send them over.

Record credits
    Bass – Rolo
    Drums – Rob Wilford
    Guitar – Peter Millson (Max)
    Vocals – Pat Fish

Other original members included:

   Johnathan Stephenson on Synthesizers 
   John Duvall on Drums 

from 1978 - 1979. Both left before the record was cut. 

![Record - The Institution-3](https://user-images.githubusercontent.com/93959968/145877633-eecd06bc-e81d-4c76-b4d1-21258bc38273.jpg)

![Record - The Institution-1](https://user-images.githubusercontent.com/93959968/145877637-99ba0727-03f4-41c3-84b2-ac3a519416cc.jpg)

![Record - The Institution-2](https://user-images.githubusercontent.com/93959968/145877639-eabf407e-c538-4b69-ae48-a09843f04904.jpg)

Images for Sonic Tonix "Don't Go Away" cat# SGS-114 that followed on the heals of The Institution released in 1980.

Record Credits
    Bass, Vocals – John Silver
    Drums, Vocals – Owen Jones
    Guitar, Vocals – Dave Goldie, Simon Mawby
    Photography By – Crispin Plaskitt
    Producer – Fish, Tonix

This is the precursor which morphed into The Tonix by late 1980 - 1982 and then eventually evolved into Pat creating Jazz Butcher in 1982. 

![Sonic Tonix-4](https://user-images.githubusercontent.com/93959968/145877682-26ca7f3d-5839-4249-8197-1503d04b537b.jpg)

![Sonic Tonix-3](https://user-images.githubusercontent.com/93959968/145877687-520a89a4-6f42-4a15-b05b-1a3da7306155.jpg)

![Sonic Tonix-2](https://user-images.githubusercontent.com/93959968/145877690-b2f1ef13-19b0-46d2-961f-72b1f2c8fc86.jpg)

![Sonic Tonix-1](https://user-images.githubusercontent.com/93959968/145877693-de08177a-4fac-402a-8414-f8dd97da8871.jpg)

**Comment by xpollen8** [comment]
Images moved into place - thanks!
