### ISSUE TITLE
Gig Press 02-20-2014 whisperinandhollerin.com review

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#79]
http://www.whisperinandhollerin.com/reviews/review.asp?id=11388&fbclid=IwAR0txX7eM_idtZTdWnUHfNSxeXqd04Lpzl2fT1WETAl3BEh18G_oC64Qyoo

**Comment by xpollen8** [comment]
http://jazzbutcher.com/press/20140920__press_quartet.html
