### ISSUE TITLE
2022 Podcast - Fifty Years of Fun - Pat Fish/The Jazz Butcher Tribute with David Barker

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#86]
Incredibly informative interview with David "Lionel Brando" Barker. From the Tonix to Early Jazz Butcher all the way through and starts off with a mention and some love thrown your way via of The JazzButcher.com website!

https://podcasts.apple.com/us/podcast/fifty-years-of-fun/id1542932551?i=1000549279324&fbclid=IwAR1pKmvPXzhd3ZNDbwBLjUOqdiCyUqDxAcQZJTQxbtOkYzurKUvxjixLKt0

"JAZ001 - Jazz Butcher Tribute episode with David Barker (Glass Records)
Back again!! We took a winter break, but we are back with a special tribute to the recently passed frontman of The Jazz Butcher. 
We start off talking about Scott’s history with the ‘Butcher, and then we chat with longtime Butcher supporter, David Barker."

**Comment by xpollen8** [comment]
Stuff that comes up: Jazz Butcher John Cale Elliot Sharp Pacific Lemon Kittens Danielle Dax The Tonix Woodentops Jacobites NRBQ Mekons Rolo McGinty John Cale English Subtitles Max Eider Pat Fish Cherry Red Glass Records Elliot Sharp In Embrace Bron Area Rip Rig & Panic Antena Everything But the Girl Bauhaus Religious Overdose David J Kevin Ayers Syd Barett Velvet Underground Lou Reed John Rivers Kevin Askins Swell Maps Felt Alan McGee Roadrunner Jonathon Richman Mark E. Smith Brix Smith The Fall KLF Camper Van Beethoven Spacemen 3 Sisters of Mercy Andrew Eldritch Big Time Records Go-Betweens Alex Chilton Redd Kross Dream Syndicate Love & Rockets REM Green On Red Tom Waits Paperhouse Teenage Fanclub The Pastels Rain Parade Oasis ———————————————————————— ** Fifty Years of Fun’s Patreon page: patreon.com/fiftyyearsoffun

**Comment by xpollen8** [comment]
Audio captured - thanks!
