### ISSUE TITLE
Highest reviews

### ISSUE THREAD

**Issue by xpollen8** [xpollen8/jazzbutcher.com#88]
<strike>https://www.backseatmafia.com/album-review-the-jazz-butcher-the-highest-in-the-land-one-final-pop-postcard-from-northamptons-foremost-gent-kickers/</strike>

<strike>Here is another "Highest" review posted by our own Dave Morgan on Facebook.
Album of the Month!
Jan 22nd https://www.mancreview.com/2022/01/album-of-the-month-the-highest-in-the-land-by-jazz-butcher/?fbclid=IwAR1fhJS6k6Anl745b78oH7JsIpPrB4wYamY85xp_z9ogTwgveu4JNCc1I5s</strike>

<strike>And a 10 stars out of 10 stars review on backseat mafia!
http://www.whisperinandhollerin.com/reviews/review.asp?id=15828&fbclid=IwAR0oJ7sCEhcA70iP4_Ll348kYFrVuMq6q7B4c4GLLN--JCG69w59u5OPWgA</strike>

<strike>Popmatters reveiw Posted by Pat's friend Paul Blinkhorn on Facebook-
https://www.popmatters.com/jazz-butcher-highest-land-review?fbclid=IwAR2dMLfv4Ta_cK3KD4xu66YtuDL1J_pNMCgTRGnlipS1Yq341UkwAJXd4Xs</strike>

<strike>Latest Pitchfork Review!
https://pitchfork.com/reviews/albums/the-jazz-butcher-the-highest-in-the-land/?fbclid=IwAR22Sj03pp21J5aCaLyVizm6ifz3IN3XnRq7RhcbQ9uutFL-5OqVLY1QD34</strike>

<strike>Louder Than War review
https://louderthanwar.com/the-jazz-butcher-the-highest-in-the-land-album-review/?fbclid=IwAR36K4Cg_mk9wNSvHbOkqiVZcy7jizTjy6A3RVIXNZj56wnpsGkvWETAqQ4</strike>

<strike>Magnet Magazine
https://magnetmagazine.com/2022/02/16/essential-new-music-the-jazz-butchers-the-highest-in-the-land/?fbclid=IwAR1xSaYCXcHqf65D4xKNRagkPEm7cxZltE8UBM-aUX0uXoH27jHgwy3OEYM</strike>

<strike>Ghetto Blaster Magazine Review
https://ghettoblastermagazine.com/features/album-reviews/new-music-friday-roll-out-02-04-22/?fbclid=IwAR03TNmrxydEFVLT1X6q_8eYrJQDi2M8RquIfLw45Hwn7BPui5etpUE7SJ0</strike>

<strike>IN FRENCH - Posted by the writer Vincent Arquillière on Facebook
http://www.popnews.com/2022/02/15/the-jazz-butcher-the-highest-in-the-land/?fbclid=IwAR2Mw0vplQHwUAYIfmTIPTbvJqN7DwJIsf6L3juLBv_vdFxH8IRWq2xLVYc</strike>

<strike>Uncut Magazine January 2022
![Jazz Butcher Highest Uncut Mag review](https://user-images.githubusercontent.com/93959968/154784561-9882e81a-9e0a-405b-a469-882e0598769a.jpg)</strike>

**Comment by Bigquestionsinc** [comment]
Awesome review! Here is nother "Highest" review posted by our own Dave Morgan on Facebook.

 Jan 22nd https://www.mancreview.com/2022/01/album-of-the-month-the-highest-in-the-land-by-jazz-butcher/?fbclid=IwAR1fhJS6k6Anl745b78oH7JsIpPrB4wYamY85xp_z9ogTwgveu4JNCc1I5s

**Comment by Bigquestionsinc** [comment]
And a 10 stars out of 10 stars review on backseat mafia!

http://www.whisperinandhollerin.com/reviews/review.asp?id=15828&fbclid=IwAR0oJ7sCEhcA70iP4_Ll348kYFrVuMq6q7B4c4GLLN--JCG69w59u5OPWgA

**Comment by Bigquestionsinc** [comment]
Latest Pitchfork Review!

https://pitchfork.com/reviews/albums/the-jazz-butcher-the-highest-in-the-land/?fbclid=IwAR22Sj03pp21J5aCaLyVizm6ifz3IN3XnRq7RhcbQ9uutFL-5OqVLY1QD34

**Comment by Bigquestionsinc** [comment]
Bucketfull of Brains Review
 https://nickbob.com/2022/02/10/the-jazz-butcher-the-highest-in-the-land/

**Comment by xpollen8** [comment]
DONE!
