### ISSUE TITLE
Red Pets lyrics Cartoon Strip by Pat Fish 1985

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#91]
Cartoon strip that Pat drew for Red Pets which he sent me way back in 1985 sent to "Barry Hale" from the Jazz Butcher Facebook group. He offered to send a Hi-Res scan as well. Hopefully Hi-Res scan coming soon!

![Red Pets cartoon by Pat](https://user-images.githubusercontent.com/93959968/152598641-da319723-88e7-41a6-a8b3-00bb18cc5808.jpg)

**Comment by xpollen8** [comment]
Oh, wow. What a treat.  What a crzay thing.

**Comment by xpollen8** [comment]
Added to JBC com V2
