### ISSUE TITLE
Goodnight Sweetheart Lyrics

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#93]
I forgot to ask Tapete Records for a copy of the lyrics when they sent me the album. Still waiting for my CD/LP in the post. Everything is backed up but, in the meantime, here is a screenshot of the lyrics of "Goodnight Sweetheart". Photo credits for the "Conspirators" on "The Highest In The Land" (posted by Pat back in June last year) coming next! 

![Goodnight Sweetheart](https://user-images.githubusercontent.com/93959968/153654546-b0cd8566-cbdc-4d8b-b331-e4883bee4dbd.jpg)

**Comment by xpollen8** [comment]
http://jazzbutcher.com/lyrics/goodnight_sweetheart.html

OCR'd and shared. Thanks, James!
