### ISSUE TITLE
Nightshift Art + Pat Nighftshift pic circa 1976-1978

### ISSUE THREAD

**Issue by Bigquestionsinc** [xpollen8/jazzbutcher.com#99]
Posted on the Jazz Butcher Facebook Group by Philip Snow!
Early "Nightshift" Artwork by Pat + Pic + John Silver post with "Nightshift" band info!

![Nightshift Artwork-1](https://user-images.githubusercontent.com/93959968/168669659-0f6610a9-1b5c-4cb7-8b88-3d3b9275bc16.jpg)

![Nightshift Artwork-2](https://user-images.githubusercontent.com/93959968/168669676-68612cff-35ce-4a31-89b9-053fe7ad6133.jpg)

![Pat Fish - Nightshift 76-77'](https://user-images.githubusercontent.com/93959968/168670043-83e2acf2-55f4-4904-8158-0a4047e2bfd0.jpg)

![Screen Shot 2022-05-16 at 12 39 41 PM](https://user-images.githubusercontent.com/93959968/168669813-982aeab4-347b-4b5a-8f50-2bc49fa0a764.png)

**Comment by xpollen8** [comment]
Images moved into new home
